name: sunny_sdk_core
author: eric@sunnyapp.co
version: 2.0.0+nullsafe.3
description: Core libraries for swagger-generated sdks
repository: https://github.com/SunnyApp/sunny_sdk_core.git
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'
dependencies: 
  firebase_auth: ^1.0.1
  buffer: ^1.1.0
  chunked_stream: ^1.4.0
  equatable: ^2.0.0
  pfile: ^1.0.1+2
  meta: ^1.3.0
  http: ^0.13.0
  logging: ^1.0.0
  path_provider: ^2.0.1
  stream_transform: ^2.0.0
  responsive_builder: ^0.3.0
  collection_diff: ^2.0.3+5
  sunny_dart: ^0.8.0+7
  dio2: ^5.0.0-nullsafety
