name: sunny_sdk_core
author: eric@sunnyapp.co
version: 1.0.0+3
description: Core libraries for swagger-generated sdks
repository: https://github.com/SunnyApp/sunny_sdk_core.git
environment: 
  sdk: '>=2.9.0 <3.0.0'
  flutter: '>=1.17.0 <3.0.0'
dependencies:
  equatable: ^1.2.5
  firebase_auth: ^0.18.3+1
  flutter:
    sdk: flutter
  google_maps_webservice: ^0.0.18
  http: ^0.12.2
  logging: ^0.11.4

#  meta_forms:
#    path: ../meta_forms
  responsive_builder: ^0.3.0
  collection_diff: ^1.0.3
#  sunny_forms:
#    path: ../sunny_forms
#  sunny_core_widgets:
#    path: ../sunny_core_widgets
  sunny_dart: ^0.5.8+3
  m_entity:
    path: ../sunny_entities/m_entity

