name: sunny_sdk_core
version: 2.5.0
description: Core libraries for swagger-generated sdks
repository: https://github.com/SunnyApp/sunny_sdk_core.git
environment: 
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=2.0.0'
dependencies: 
  firebase_auth: ^4.1.4
  buffer: ^1.1.1
  chunked_stream: ^1.4.1
  collection: ^1.16.0
  equatable: ^2.0.5
  meta: ^1.8.0
  intl: ^0.17.0
  http: ^0.13.5
  logging: ^1.0.2
  path_provider: ^2.0.11
  stream_transform: ^2.0.0
  timezone: ^0.9.0
  dio: ^4.0.4
  collection_diff: 
    git: 
      url: git@github.com:SunnyApp/collection_diff
      ref: trippi_app
  pfile: 
    git: 
      url: git@github.com:SunnyApp/pfile
      ref: trippi_app
  flexidate: 
    git: 
      url: git@github.com:TrippiApp/flexidate
      ref: trippi_app
  sunny_dart: 
    git: 
      url: git@github.com:SunnyApp/sunny_dart
      ref: trippi_app
  dartxx: 
    git: 
      url: git@github.com:ericmartineau/dartxx.git
      ref: trippi_app
  flutter: 
    sdk: flutter
