name: sunny_sdk_core
author: eric@sunnyapp.co
publish_to: none
description: Core libraries for swagger-generated sdks
repository: https://github.com/SunnyApp/sunny_sdk_core.git
environment: 
  sdk: '>=2.9.0 <3.0.0'
  flutter: '>=1.17.0 <3.0.0'
dependencies: 
  firebase_auth: ^3.9.0
  dio: ^4.0.6
  buffer: ^1.0.7
  chunked_stream: ^1.2.0
  equatable: ^2.0.5
  http: ^0.13.5
  logging: ^1.0.2
  path_provider: ^2.0.11
  stream_transform: ^2.0.0
  responsive_builder: ^0.4.2
  pfile: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/pfile
  collection_diff: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/collection_diff
  sunny_dart: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_dart
  m_entity: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_entities/m_entity
dependency_overrides: 
  pfile: 
    path: ../pfile
  sunny_dart: 
    path: ../sunny_dart
  m_entity: 
    path: ../sunny_entities/m_entity
