name: sunny_sdk_core
version: 2.5.0
description: Core libraries for swagger-generated sdks
repository: https://github.com/SunnyApp/sunny_sdk_core.git
environment: 
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'
dependencies: 
  firebase_auth: ^3.3.18
  buffer: ^1.1.1
  chunked_stream: ^1.4.1
  collection: ^1.16.0
  equatable: ^2.0.3
  meta: ^1.7.0
  intl: ^0.17.0
  http: ^0.13.4
  logging: ^1.0.2
  path_provider: ^2.0.10
  stream_transform: ^2.0.0
  timezone: ^0.8.0
  dio: ^4.0.6
  collection_diff: 
    path: /Users/ericm/sunny/local_plugins/collection_diff
  pfile: 
    path: /Users/ericm/sunny/local_plugins/pfile
  flexidate: 
    path: /Users/ericm/sunny/local_plugins/flexidate
  sunny_dart: 
    path: /Users/ericm/sunny/local_plugins/sunny_dart
  dartxx: 
    path: /Users/ericm/sunny/local_plugins/dartxx
  flutter: 
    sdk: flutter
