name: sunny_sdk_core
author: eric@sunnyapp.co
version: 1.0.0+3
description: Core libraries for swagger-generated sdks
repository: https://github.com/SunnyApp/sunny_sdk_core.git
environment: 
  sdk: '>=2.9.0 <3.0.0'
  flutter: '>=1.17.0 <3.0.0'
dependencies: 
  sunny_dart: ^0.5.8+2
  logging: ^0.11.4
  http: ^0.12.2
  flutter: 
    sdk: flutter
