// DO NOT EDIT THIS FILE.  IT IS GENERATED AUTOMATICALLY AND YOUR CHANGES WILL BE OVERWRITTEN

import 'package:equatable/equatable.dart';

class GeoLocation extends Equatable {
  final double? lat;
  final double? lon;

  GeoLocation({this.lat, this.lon});

  @override
  List<Object?> get props => [lat, lon];

  static GeoLocation? fromJson(dyn) {
    if (dyn == null) return null;
    if (dyn["lat"] != null && dyn["lon"] != null) {
      return GeoLocation(
          lat: dyn["lat"] as double?, lon: dyn["lon"] as double?);
    } else {
      return null;
    }
  }
}
